export const types = {
    CHANGE_NUMBER: "CHANGE_NUMBER",
    CHANGE_NUMBER2: "CHANGE_NUMBER2",
    ADD_NUMBER: "ADD_NUMBER",
    SUBTRUCT_NUMBER: "SUBTRUCT_NUMBER",
    MULTIPLY_NUMBER: "MULTIPLY_NUMBER",
    DIVIDE_NUMBER: "DIVIDE_NUMBER"
}